name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"    # every day at 18:00 UTC
  workflow_dispatch:       # allows manual runs

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Aadya-Madankar/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate 3D contribution graph"
          git push
